---
- import_tasks: selinux.yml

- name: ensure that nginx is installed
  yum:
    pkg: nginx
    state: present

- name: populate an nginx config
  template:
    src: site.conf.j2
    dest: /etc/nginx/conf.d/site.conf
  notify: reload nginx

- name: create the root folder
  file:
    name: "{{ server_root_directory }}"
    state: directory

- name: provision the index file
  template:
    src: index.html.j2
    dest: "{{ server_root_directory }}/index.html"

# TODO use seboolean module to make proxy

- name: enable nginx service
  service:
    name: nginx
    state: started
    enabled: yes
